# Generated by Django 3.2.14 on 2022-07-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='jdjbyudb', upload_to='', verbose_name='gallery'),
            preserve_default=False,
        ),
    ]
